package com.example.intelligentpark.pojo;

/**
 * Created by 李盛乐 on 2018.3.9.
 */

import java.util.Date;

public class Account {

    public Account(String phone, String name, String password) {
        this.phone = phone;
        this.name = name;
        this.password = password;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.phone
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.name
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.sex
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    private String sex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.type
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.regdate
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    private Date regdate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column account.password
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.phone
     * @return  the value of account.phone
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.phone
     * @param phone  the value for account.phone
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.name
     * @return  the value of account.name
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.name
     * @param name  the value for account.name
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.sex
     * @return  the value of account.sex
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.sex
     * @param sex  the value for account.sex
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.type
     * @return  the value of account.type
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.type
     * @param type  the value for account.type
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.regdate
     * @return  the value of account.regdate
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.regdate
     * @param regdate  the value for account.regdate
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column account.password
     * @return  the value of account.password
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column account.password
     * @param password  the value for account.password
     * @mbg.generated  Sat Mar 10 14:25:31 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    public String toString(){
        return phone +"  "+password;
    }

}